definitions:
  hadith.Data:
    properties:
      arabic:
        type: string
      number:
        type: integer
      translate:
        $ref: '#/definitions/hadith.Translate'
    type: object
  hadith.ResponseHadith200Ok:
    properties:
      author:
        type: string
      data:
        items:
          $ref: '#/definitions/hadith.Data'
        type: array
      page:
        type: integer
      per_page:
        type: integer
      status_code:
        type: integer
      total_hadith:
        type: integer
    type: object
  hadith.Translate:
    properties:
      id:
        type: string
    type: object
info:
  contact:
    email: adiatma.mail@gmail.com
  title: Adiatma Tech API
  version: v0.1.0
paths:
  /hadith/{author}:
    get:
      parameters:
      - description: author
        in: path
        name: author
        required: true
        type: string
      - description: page
        in: query
        name: page
        type: string
      - description: perPage
        in: query
        name: perPage
        type: string
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/hadith.ResponseHadith200Ok'
            type: array
  /hadith/list/authors:
    get:
      responses:
        "200":
          description: OK
          schema:
            items:
              type: string
            type: array
swagger: "2.0"
