name: Build & Push

on:
  push:
    branches: [ "main" ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write

    steps:
      - uses: docker/setup-buildx-action@v2

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GH_TOKEN }}

      - id: meta
        uses: docker/metadata-action@v4
        with:
          images: "ghcr.io/${{ github.repository }}/home"
          tags: latest

      - uses: docker/build-push-action@v4
        with:
          context: "{{ defaultContext }}:home"
          tags: ${{ steps.meta.outputs.tags }}
          push: true
